import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.scss";
import { Open_Sans } from "next/font/google";
import ReduxProvider from "@/store/redux-provider";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DemoContainer } from "@mui/x-date-pickers/internals/demo";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import LocalizationWrapper from "@/libs/localization";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"], // Add more weights if needed
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} `}>
        <ReduxProvider>
          <LocalizationWrapper>
            <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
          </LocalizationWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
